<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">calculateModulus</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICAgIElEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KDQogICAgdHJ5
IHsNCiAgICAgICAgLy8gRXh0cmFjdCBpbnB1dHMgZnJvbSB0aGUgcGlwZWxpbmUNCiAgICAgICAg
aW50IGRpdmlkZW5kID0gSURhdGFVdGlsLmdldEludChwaXBlbGluZUN1cnNvciwgImRpdmlkZW5k
Iik7DQogICAgICAgIGludCBkaXZpc29yID0gSURhdGFVdGlsLmdldEludChwaXBlbGluZUN1cnNv
ciwgImRpdmlzb3IiKTsNCg0KICAgICAgICAvLyBDaGVjayBmb3IgZGl2aXNpb24gYnkgemVybw0K
ICAgICAgICBpZiAoZGl2aXNvciA9PSAwKSB7DQogICAgICAgICAgICB0aHJvdyBuZXcgQXJpdGht
ZXRpY0V4Y2VwdGlvbigiRGl2aXNpb24gYnkgemVybyIpOw0KICAgICAgICB9DQoNCiAgICAgICAg
Ly8gQ2FsY3VsYXRlIG1vZHVsdXMNCiAgICAgICAgaW50IHJlc3VsdCA9IGRpdmlkZW5kICUgZGl2
aXNvcjsNCg0KICAgICAgICAvLyBBZGQgdGhlIHJlc3VsdCB0byB0aGUgcGlwZWxpbmUNCiAgICAg
ICAgSURhdGFVdGlsLnB1dChjdXJzb3IsICJyZXN1bHQiLCByZXN1bHQpOw0KICAgIH0gY2F0Y2gg
KEV4Y2VwdGlvbiBlKSB7DQogICAgICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOw0K
ICAgIH0gZmluYWxseSB7DQogICAgICAgIGN1cnNvci5kZXN0cm95KCk7DQogICAgfQ0KfQ0KCQ==
</value>
</Values>
